### ISSUE TITLE
Image Labels

### ISSUE THREAD

**Issue by benplum** [bigtreecms/BigTree-CMS#152]
Would be great if image uploads and galleries automatically displayed their min dimensions in the sub-label.

**Comment by timbuckingham** [comment]
I think this got fixed at some point, looks like it's working now anyway:
<img width="488" alt="screen shot 2016-05-20 at 4 33 34 pm" src="https://cloud.githubusercontent.com/assets/1420086/15441411/af504908-1ea8-11e6-9780-35d81d6532ae.png">
