### ISSUE TITLE
Dropdowns disconnected

### ISSUE THREAD

**Issue by benplum** [bigtreecms/BigTree-CMS#170]
![screen shot 2015-02-10 at 10 02 14 am](https://cloud.githubusercontent.com/assets/1130075/6129367/0be9f0f8-b10c-11e4-857d-5411e3c5ebd7.png)

**Comment by timbuckingham** [comment]
Chrome?

**Comment by benplum** [comment]
And firefox 
![screen shot 2015-02-10 at 10 25 43 am](https://cloud.githubusercontent.com/assets/1130075/6129841/31b38544-b10f-11e4-9e4d-ca8588ff64b3.png)

**Comment by timbuckingham** [comment]
Should be fixed here:
https://github.com/bigtreecms/BigTree-CMS/commit/cad3576e26a04782dbe807715e789b33f20a8aa4
