### ISSUE TITLE
Internal Server Error and MySQLi problems

### ISSUE THREAD

**Issue by PierBover** [bigtreecms/BigTree-CMS#171]
So I installed BigTree a few times and always got an Internal Server Error. The installation finishes in a second or so, but when trying to access the admin or demo site it crashed.

I tried using basic routing and changing permissions to 777, but I still get the error.

This is the error in the Apache log:
> SoftException in Application.cpp:261: File "**********/bigtreetest/site/index.php" is writeable by group

After some googling I changed permissions to 755 and now I get some mysqli errors.

> Warning: mysqli::mysqli(): (28000/1045): Access denied for user 'elhossmg_mysql'@'localhost' (using password: YES) in **********/bigtreetest/core/inc/bigtree/sql.php on line 16

> Warning: mysqli::query(): Couldn't fetch mysqli in **********/bigtreetest/core/inc/bigtree/sql.php on line 17

> Warning: mysqli::query(): Couldn't fetch mysqli in **********/bigtreetest/core/inc/bigtree/sql.php on line 18

Etc.

The mysql user is OK, because the I've checked in PhpMyAdmin and the installer created the tables. The MySQLi extension is installed and has version 5.5.41

What is wrong?

**Comment by timbuckingham** [comment]
What's your server environment like? I've never seen the SoftException error, so I'm curious what configuration would cause that.

My best guess for the SQL issue is that the installer didn't properly write the username and password into /custom/environment.php -- verify the proper settings are there under the "// Database Environment" section.

**Comment by PierBover** [comment]
It's just the typical linux shared hosting.

I've checked the database environment and it's all there...

I'm thinking that maybe I messed up when changing permissions. I will try to reinstall again with a php.ini to make triple sure the options (magic quotes, etc) are ok.

**Comment by timbuckingham** [comment]
Do you mind sharing what host it is? I'd love to try to get it working on as many hosts as possible!

Thanks!

**Comment by PierBover** [comment]
Sure, it's Namecheap.

**Comment by timbuckingham** [comment]
Thanks! I'll try to get a Namecheap instance up and running

**Comment by timbuckingham** [comment]
I ran into the same SoftException issue as you -- I'm going to look into different permission setups when Apache is running as the user that owns the files (rather than "apache" as it does on non-shared hosts). Hopefully that will rectify the issue.

I didn't notice any MySQL issues, though -- after setting /site/ and /site/index.php to 755 the example site started up for me.

**Comment by PierBover** [comment]
I reinstalled again with a php.ini and got the same SoftException.

I changed /core/example-site/site/index.php to 755 but still nothing...

**Comment by timbuckingham** [comment]
The example site folder shouldn't need any changing of permissions -- the contents of that folder are copied into other directories. For me it was just /site/ and /site/index.php that needed permissions changed to 755. It's worth noting as well that the cPanel file manager failed to change the permissions for me -- I had to SFTP in and do it that way.

**Comment by PierBover** [comment]
Ok, so I changed the permissions on the correct ones (/site/ and /site/index.php) and I got  to the same mysqli errors.

> Warning: mysqli::mysqli(): (28000/1045): Access denied for user '*******'@'localhost' (using password: YES) in *******/public_html/bigtreecms/core/inc/bigtree/sql.php on line 16

> Warning: mysqli::query(): Couldn't fetch mysqli in *******/public_html/bigtreecms/core/inc/bigtree/sql.php on line 17

> Warning: mysqli::query(): Couldn't fetch mysqli in *******/public_html/bigtreecms/core/inc/bigtree/sql.php on line 18

> Warning: mysqli::query(): Couldn't fetch mysqli in *******/public_html/bigtreecms/core/inc/bigtree/sql.php on line 98

> Warning: sqlquery(): Couldn't fetch mysqli in *******/public_html/bigtreecms/core/inc/bigtree/sql.php on line 99

> Fatal error: Call to a member function fetch_assoc() on a non-object in *******/public_html/bigtreecms/core/inc/bigtree/sql.php on line 133

**Comment by timbuckingham** [comment]
I would try adding a new user to the database through cPanel and that new user/pass combination. Not sure what could be going on otherwise.

**Comment by PierBover** [comment]
I created a new DB user, then changed the data in config.environment.php (which btw had no data this time) and I still get the same mysqli errors...

http://www.elhostingdepier.com/bigtreecms/
http://www.elhostingdepier.com/bigtreecms/admin/

I granted all permissions to the user on the DB I'm using. Is there anything else I have to do in cPanel with the DB user?

**Comment by timbuckingham** [comment]
Did you assign the user to the database? I missed that the first time I went through the process -- there's an "Add User To Database" section in cPanel where you have to assign the user to a database and then grant all the permissions to it.

**Comment by PierBover** [comment]
It works!!!

I messed up again, and changed the DB data in the /core instead of /custom

**Comment by timbuckingham** [comment]
Awesome! Glad you got it working :)

**Comment by PierBover** [comment]
Thanks for the help!

I guess cPanel doesn't like all that creating and deleting databases.

If you solve the permissions thing everything should be smooth in Namecheap :)
