### ISSUE TITLE
Photo Gallery does not work on 4.1.4 version

### ISSUE THREAD

**Issue by christianldm** [bigtreecms/BigTree-CMS#172]
trying to work out when I select a photo gallery field type does not select the image and not getting the function
I know there is a new version is that going to solve the problem?

**Comment by timbuckingham** [comment]
I'm not 100% sure what you're asking here -- I did discover a bug in the custom photo gallery that the example site in the BigTree 4.1 installer uses. If you put in an invalid link into the Link field when adding an image it will fail to validate and won't let you submit. Is that what you're encountering or is it something else?

**Comment by christianldm** [comment]
when I select photo gallery field and want to upload an image does not upload or let me edit the ones form the demo is has to do with version ?

**Comment by christianldm** [comment]
I want to make a video and image gallery therefore I'm using photo gallery field type but when I want to upload an image does not upload it

**Comment by timbuckingham** [comment]
Do you receive an error of any kind after submitting the form? If so, could you attach a screenshot?

**Comment by christianldm** [comment]
not error but in the console show error of a function Uncaught ReferenceError: CustomPhotoGallery is not defined

**Comment by timbuckingham** [comment]
Is demo.js being loaded into the HTML for you on the form? That should include CustomPhotoGallery.

**Comment by christianldm** [comment]
not it's not load it should I add it on settings.php to be loaded?

**Comment by timbuckingham** [comment]
It should loaded in settings.php, the example site default settings.php should have something like this:

$bigtree["config"]["admin_js"] = array("demo.js");

That causes it to load demo.js which contains the custom photo gallery. If you want to use the standard photo gallery that doesn't include a link and attribution field you can just delete /custom/admin/form-field-types/draw/photo-gallery.php and /custom/admin/form-field-types/process/photo-gallery.php

**Comment by christianldm** [comment]
oh great it works somehow the array was empty so demo.js was not loaded 
thank's that's very helpful

**Comment by timbuckingham** [comment]
No problem, happy to help!
