### ISSUE TITLE
Field type requests

### ISSUE THREAD

**Issue by benplum** [bigtreecms/BigTree-CMS#173]
- Media gallery (youtube/vimeo)
- Single media (image and youtube/vimeo)
- Captions on single media (stored as array)

**Comment by benplum** [comment]
- Link finder
- Character count text
- Read only text
- Hidden value
- Year select (with custom ranges)
- Section break (form fancier forms)

**Comment by benplum** [comment]
- Separate Credit AND Caption fields in Media Galleries and Single Media (possibly the ability to customize the extra "content" associated to media, similar to a Matrix but focused?)

**Comment by timbuckingham** [comment]
Media Gallery: https://www.bigtreecms.org/extensions/details/com.fastspot.media-gallery-field-type/
Single Media / Video: https://www.bigtreecms.org/extensions/details/com.fastspot.video-field-type/
Link Finder: https://www.bigtreecms.org/extensions/details/com.fastspot.link-finder-field-type/
Character Count Text: https://www.bigtreecms.org/extensions/details/com.fastspot.characer-count-field-type/
Hidden Value: https://www.bigtreecms.org/extensions/details/com.fastspot.hidden-value-field-type/
Read Only Value: https://www.bigtreecms.org/extensions/details/com.fastspot.read-only-value-field-type/
Section Break: https://www.bigtreecms.org/extensions/details/com.fastspot.section-break-field-type/

I think the only one missing right now is Year select. The last request is part of Media Gallery.
