### ISSUE TITLE
Esc on file browser

### ISSUE THREAD

**Issue by benplum** [bigtreecms/BigTree-CMS#175]
doesn't close the browser, but removes the transparent overlay.

**Comment by timbuckingham** [comment]
Should be fixed here: https://github.com/bigtreecms/BigTree-CMS/commit/9aed30c7e11549d9143e6fb0359a14de0c692de5

The escape key hooks weren't being removed on the dialogs for adding a file or folder which made the behavior all messed up the next time the escape key was hit.
