### ISSUE TITLE
'_' files in routed templates

### ISSUE THREAD

**Issue by benplum** [bigtreecms/BigTree-CMS#184]
Should be hidden. I know it's a weird edge case and requires hacking the URL, but hitting a page like 'domain.com/routed-tempalte/_header/' will draw a page that is sometimes completely broken depending on the include pattern.

**Comment by timbuckingham** [comment]
Fixed: https://github.com/bigtreecms/BigTree-CMS/commit/ad429083eff7700a258773009e3491e280b8f674

**Comment by benplum** [comment]
My only concern is that custom underscores are still accessible, "_nav" or "_list".

**Comment by timbuckingham** [comment]
Changing the routing behavior for those files could be problematic in the event that anyone is using a file beginning with an underscore as something other than a partial. _header.php and _footer.php have core behavior which has always existed so we can safely stop those from routing.

We could change the behavior and make all files beginning with _ non-routeable in 4.2 but I don't know how valuable it is just to throw 404s on URLs that would only be stumbled upon by URL manipulation. Any thoughts on this @matthisamoto @bonchampion @nhall ?

**Comment by benplum** [comment]
I guess opens up a larger conversation about the routing methodologies. 

Sometimes the open-ended nature of routed templates is both good and bad. We can drop new files in and they become active urls, but we also have to manually catch the situations where a url isn't actually valid in the site. Of course this very edge case, but if someone is hacking a url they may produce urls containing duplicate module-based content, depending on how the routed template is set up. Or they could load a "page" that's really just a random include dumped into the default layout, if that include doesn't actually throw an error. 

I really like the idea of 'registering' url patterns similar to the url tokenization in WP, possibly through the related module's class. Maybe it even hooks into any nav, breadcrumb and sitemap drawing code? It could always default to the current system if a patterns isn't set up, but this would give us a way to avoid writing custom 404 handlers in every routed template.

**Comment by timbuckingham** [comment]
That's definitely worth exploring, something like a registerRoute default class method that could accept a route, file to drive the route, navigation title, and whether to accept additional wildcard routes?

We could check the route registry for routed templates with associated module classes, if it's empty route the old way.

I think the route registry approach might work well for things we previously hacked up like accepting project URLs without something like "details". Maybe register a wildcard... like `$this->registerWildcardRoute('details.php')` that would tell the routing to send everything that doesn't match another route to details.php.
