### ISSUE TITLE
getTagsForItem

### ISSUE THREAD

**Issue by benplum** [bigtreecms/BigTree-CMS#187]
Just curious why doesn't this include the tag's route? Requires 'urlifying' in the template to create a link.

**Comment by timbuckingham** [comment]
No good reason at all, I imagine. It's not even consistent with BigTreeCMS::getTagsForPage. Unfortunately it returns a flat array of tags at the moment. I guess we could break backwards compatibility here if the use case is worth it (which I can see it being, route data is pretty valuable).
