### ISSUE TITLE
Global default Gravatar

### ISSUE THREAD

**Issue by mdewyer** [bigtreecms/BigTree-CMS#189]
Consider moving the 

$default = "http://www.bigtreecms.org/images/bigtree-gravatar.png";

Gravatar variable from inside the utils.php file to the settings.php file and make it something like $bigtree["config"]["gravatar"]["default"]. That way it's easy to change, globally accessible (even if just for the gravatar function) and can withstand version updates.

**Comment by timbuckingham** [comment]
Totally agree with you -- that was a pretty big oversight to not let users set an alternate default gravatar. I'm actually in the process of fixing the gravatar system so that it will load over HTTPS properly so I'll make this fix at the same time.
