### ISSUE TITLE
Control Module Admin Visibility

### ISSUE THREAD

**Issue by mdewyer** [bigtreecms/BigTree-CMS#190]
Consider adding the option for modules to only be visible to developers. That way if it's a module that only the developer will maintain for a site, the "normal" admin of the site wouldn't see it under site.com/admin/modules/ and be able to mess with it.

**Comment by timbuckingham** [comment]
I like it! Makes sense given we already support developer-only settings.

**Comment by mdewyer** [comment]
Excellent! I apologize for all the recommendations. I'm just loving BigTree and digging into it as we develop out some sites and modules for it, and just mentioning things that come up as we come across them. Thank you so much for listening to the feedback!

**Comment by timbuckingham** [comment]
No need to apologize, they're all great ideas! We love outside perspectives and are glad you're enjoying BigTree -- we always love to hear about sites launching on BigTree so hit us up on the forums with launch celebrations and we'll spread the love :)

**Comment by mdewyer** [comment]
Great! And will do!

**Comment by timbuckingham** [comment]
Added this here:
https://github.com/bigtreecms/BigTree-CMS/commit/f668dbc657d5c8f642b9f68f89e5305dffa65194
