### ISSUE TITLE
SendGrid Email Delivery Service

### ISSUE THREAD

**Issue by zumbrunnen** [bigtreecms/BigTree-CMS#192]
Hi there

I've created an additional Email Delivery service: [SendGrid](https://www.sendgrid.com)

Please (re)view this feature here: https://github.com/zumbrunnen/BigTree-CMS/tree/sendgrid

The branch is based on the `master` branch. Let me know if I shall rebase it on one of the dev-branches (which one?). :confused: If you want, I'll file a PR to the branch of your choice.

Cheers!

**Comment by timbuckingham** [comment]
That's excellent! I guess the 4.2-devel branch would be appropriate for the pull request. 4.3 is a long way off so better to get this in sooner than later. Thanks for your contribution! I'll sign up for a SendGrid account and do some testing.

**Comment by zumbrunnen** [comment]
OK, I'll do a rebase and file a PR.

I've tested the feature by configuring the service and then hit the "Forgot Password" link :wink:. Additional testing would be great!

**Comment by timbuckingham** [comment]
Excellent! The implementation worked very well. Thanks again for the contribution! It's merged into 4.2-devel now and will see the light of day in the 4.2.1 release.
