### ISSUE TITLE
Bigtree CMS 4.2 Cookies disclosing Username and Password

### ISSUE THREAD

**Issue by sumitingole** [bigtreecms/BigTree-CMS#196]
Bigtree CMS 4.2

Vulnerability -  Critical Information Disclosing by Cookie (Username and password) 

Severity : Critical

Reported By - Sumit Ingole (Security analyst @Suma soft Pvt. Ltd Pune India)
=============================================================
![username and password](https://cloud.githubusercontent.com/assets/11312706/7105219/f6a4835c-e12b-11e4-89d8-f8fbd88489b6.PNG)

**Comment by timbuckingham** [comment]
What would you recommend for a "remember me" system that is more secure? We could of course encrypt the client side information with a key that only the server knows (which would be more secure if the concern is someone with local access brute forcing the hashed password). That wouldn't prevent someone from copying the saved email/pass and logging in as them, though.

Thanks for the help! I'll be looking over the other two security disclosures and fixing them ASAP.

**Comment by sumitingole** [comment]
As i mentioned your CMS is vulnerable to XSS vulnerability, an attacker can hijack admin session id ,username and password and by using those attacker can login himself as admin remotely.

for "remember me"  i need to do some finding. I will let you know as soon as i found it.

**Comment by timbuckingham** [comment]
Thanks! I'm working on cleaning up the XSS vulnerabilities now, hope to have them fixed in an hour or so.

**Comment by timbuckingham** [comment]
What do you think of the persistent login cookie approach outlined here?
http://jaspan.com/improved_persistent_login_cookie_best_practice

**Comment by sumitingole** [comment]
it's good. you can use it session management.

**Comment by timbuckingham** [comment]
Excellent, thank you for your contributions to the security of BigTree! I'll get started on implementing that system today.
