### ISSUE TITLE
Missing HTTPOnly flag in session cookie

### ISSUE THREAD

**Issue by sumitingole** [bigtreecms/BigTree-CMS#197]
Bigtree CMS 4.2

Vulnerability - Missing HTTPOnly Flag in session cookie

Severity : HIgh (As it is vulnerable to XSS)

Reported By - Sumit Ingole (Security analyst @Suma soft Pvt. Ltd Pune India)
=============================================================

![missing httponly flag](https://cloud.githubusercontent.com/assets/11312706/7105237/9c540a02-e12c-11e4-8475-4f6bd18ef4ab.PNG)

**Comment by timbuckingham** [comment]
Thanks! Wasn't even aware of the HttpOnly setting. I've also applied it to login cookies.
