### ISSUE TITLE
Bug on installing extension with new field types

### ISSUE THREAD

**Issue by jmason03** [bigtreecms/BigTree-CMS#199]
When installing an extension that adds a field type, the use cases of the field type from the manifest is not inserted into the database because it is still in an array when added to the SQL query. This causes a blank field to get inserted which causes PHP to throw illegal string offset warnings when trying to edit the use cases of the field type in Developer mode of BigTree. 

Fix submitted in commit: 33f5bdabf3129c24c563b4468d0ee0a482d44500

**Comment by timbuckingham** [comment]
Thanks! I left off the add/edit changes as they shouldn't be needed unless a field type has broken database data (and the "add" file already sets defaults, so it would have to be broken post data somehow).
