### ISSUE TITLE
Matrix fields with title having phone/url sub type not displaying

### ISSUE THREAD

**Issue by jmason03** [bigtreecms/BigTree-CMS#201]
Matrix fields that have a text field with a sub type of url or phone number set to be the title do not display the title in the matrix list after updating.

**Comment by jmason03** [comment]
Fix submitted in commit: a64cfcdd7af7ad30b8f3312936d634373353e506

**Comment by timbuckingham** [comment]
Sorry for the delay in reviewing this -- I was on vacation for a week and now I'm out for a funeral. Hopefully I'll have time to check this out and merge in fixes tomorrow!

**Comment by timbuckingham** [comment]
Thanks! The commit referenced above should integrate your phone solution along with support for Name and Address text subtypes when using those as the title of a Matrix entry.
