### ISSUE TITLE
Auto-Update Grouped Views Using Featured Icons

### ISSUE THREAD

**Issue by jmason03** [bigtreecms/BigTree-CMS#202]
This is useful if a user has a grouped view where the grouping occurs based on whether or not an item is "featured" using the featured icon. If it is, then the content should be reloaded with an ajax call to display the change in the clicked item's grouping. This prevents the user from having to refresh the page to see their changes. 

Solution offered in commit: 02c2f4c4977646698b673a2fec1210276445084c

**Comment by timbuckingham** [comment]
Interesting -- so you're using the grouped view to split out items that have featured = "on" and featured = ""? Never thought of using it that way before! I guess this would also be useful for splitting out archived and approved items.

I'll try to check out the commit tomorrow and test it in action :)

**Comment by timbuckingham** [comment]
I just pushed a commit that I think replicates what you were doing in your commit but simplifies it a bit (and also adds support for approved and archived). It should also add proper group names (i.e. Featured and Normal vs "" and "on").

If I didn't understand the goal properly let me know, but I think it's a cool feature update either way :)
