### ISSUE TITLE
Editing Matrix with Required Photo Bug

### ISSUE THREAD

**Issue by jmason03** [bigtreecms/BigTree-CMS#203]
When editing a matrix field with a required photo and the photo has already been uploaded, the field incorrectly fails validation because the HTML structure is different than how it is referenced in the JS.

An attempted solution in commit: a75a7825d3202edfd6b8771a2809e42096e2d6f8

**Comment by timbuckingham** [comment]
I can't replicate this on 4.2-devel but I can on 4.2.1. I *think* this commit fixed it:
https://github.com/bigtreecms/BigTree-CMS/commit/5e76b8577dceaf3cf596322eaa206f9320e51a77

If it's still buggy for you after that let me know!

**Comment by jmason03** [comment]
Worked great for me! Thanks
