### ISSUE TITLE
Parent ID missing in pending page entries

### ISSUE THREAD

**Issue by jmason03** [bigtreecms/BigTree-CMS#204]
When a page that was previously published was saved by an editor and entered into the pending change table using the submitPageChange function, the pending_page_parent was not added and resulted in all entries having a 0 placed in by default. 

Solution offered in commit: c9f5e87602935db334dbf45d529e5ac65603712f

**Comment by timbuckingham** [comment]
I'm not quite following here -- pending_page_parent is only applicable to pages that aren't yet published as editors aren't able to change the parent ID of a page. Is there some kind of unexpected behavior occurring alongside the 0 entry?

**Comment by jmason03** [comment]
Oh ok, that makes sense. I was using the value as a part of a custom piece I'm building involving user permissions/approval of pending pages. I needed a pending pages parent ID value and it was only storing it correctly if the pending page was a new page rather than an edit. So if that is the expected behavior then I'll just consider my addition as part of my overall custom modifications.

**Comment by timbuckingham** [comment]
Cool, thanks for the explanation! You can always use the BigTreeCMS class's getPendingPage to grab both the parent ID and the pending changes as well if you need to.
