### ISSUE TITLE
Stored XSS while creating a new user

### ISSUE THREAD

**Issue by a0xnirudh** [bigtreecms/BigTree-CMS#205]
Hello everyone,

While creating a new user, give a valid email, provide the name as **name"><svg onload="alert(2)";**  and save the user with a valid password. When we go to **view users** again, it will trigger the XSS. 

![screenshot-1](https://cloud.githubusercontent.com/assets/5573458/8359776/0eaa3eee-1b86-11e5-9a1a-eb08191cf9c9.png)

The payload gets directly saved into the database and is executed when we go to the **view users** page. This happens because the name field is not properly sanitized before saving the data into the database.

**Comment by lucif3rr** [comment]
All other common user input fields look properly sanitized. I think the name field is not passed through **htmlspecialchars()**. Can someone confirm this ?

**Comment by timbuckingham** [comment]
Looking into this!

**Comment by timbuckingham** [comment]
Thanks for the bug report -- it looks like names and company names weren't being properly htmlspecialchar'd before inserting them into the database. That should be fixed in the referenced commit above!

**Comment by fgeek** [comment]
For reference CVE request for this vulnerability was done in oss-security mailing list http://www.openwall.com/lists/oss-security/2015/06/26/5 but never assigned as far as I know.
