### ISSUE TITLE
Slash and no-slash requests deliver the same content

### ISSUE THREAD

**Issue by randyhook** [bigtreecms/BigTree-CMS#214]
As per the Google Webmaster Central Blog (http://googlewebmastercentral.blogspot.com/2010/04/to-slash-or-not-to-slash.html) the Google crawler is usually able to handle a site that delivers both slash and no-slash requests (e.g. site.com/trees/ and site.com/trees) without problems, although they state that it is a less-than-optimal solution.

Therefore, I have added some logic to the router that determines if the request does not have a trailing slash and adds it if necessary. The router then 301 redirects the request to the trailing slash page, as recommended by Google: Use a 301 redirect from the duplicate to the preferred version.

I think the next thing to add however would let the developer decide if they want trailing slashes added or removed.

Link to branch: https://github.com/MindscapeSolutions/BigTree-CMS/tree/trailing-slash

**Comment by randyhook** [comment]
I've added a config setting that allows the dev to set the handling of the trailing slash. The settings are either "none", "append" or "remove".

Link to branch: https://github.com/MindscapeSolutions/BigTree-CMS/tree/trailing-slash

**Comment by timbuckingham** [comment]
Just wanted to let you know this is on my radar -- just swamped with client work at the moment!

**Comment by timbuckingham** [comment]
Thanks Randy! I simplified the implementation a bit (checks for presence of trailing slash occur now in launch.php where the other routing checks occur and set a global that is checked in the router) and also added support for this setting at install time.

The commit merging this with the 4.2-devel branch is here:
https://github.com/bigtreecms/BigTree-CMS/commit/38abf656196083d2da837c2ce5323b555fda20c8

Let me know if you have any questions or if I screwed anything up moving things around :)

**Comment by randyhook** [comment]
Looks great Tim! That's an excellent idea placing the option in the install.

The only thing I noticed is that the new setting is not carried over into custom/settings.php when you install the example site.

**Comment by timbuckingham** [comment]
Good catch! I just pushed a commit to fix that -- looks like that demo site setting hasn't been updated in a while. I've got it on the design team's radar that I'd like a much more comprehensive and re-usable (component wise) example site in the 4.4 release -- hopefully we can get that thing into a better state soon!
