### ISSUE TITLE
Fix for Extension Build

### ISSUE THREAD

**Issue by randyhook** [bigtreecms/BigTree-CMS#215]
I was having problems when trying to build an extension. Both my included templates and settings were not being set in the manifest. Thus, when trying to install the extension on a clean site, some of my components were missing.

I ran through the code and found the following issues, which I'd be curious to know if there is actually a problem here, or if I'm overlooking something. Both issues are in core/admin/modules/developer/extensions/build/create.php:

Lines 136-139
```
if (strpos($template,"*") === false) {
	sqlquery("UPDATE bigtree_templates SET extension = '$extension', id = CONCAT('$extension*',id) WHERE id = '".sqlescape($template)."'");
}
$package["components"]["templates"][] = $cms->getTemplate($template);

```

1. Assume I have an extension named com.test.myextension with a template named mytemplate.
2. We will enter the block at 137 because there is no asterisk in my template name.
3. The query will run and my template will have a new id: com.test.myextension*mytemplate.
4. Line 139 runs and attempts to get the template with its old id, mytemplate, which no longer exists.

The same is true for the extension's settings at Lines 87-90. Its attempting to query a setting by its old id.

So unless I'm overlooking something, I have made a fix that simply queries for the new ids. The link to the branch is at: https://github.com/MindscapeSolutions/BigTree-CMS/tree/extension-build-fix

**Comment by timbuckingham** [comment]
I found a few other issues in there as well (settings would get their ID manged more and more each time you re-saved, callouts had the same issues as templates).

I think I have the fix in place here:
https://github.com/bigtreecms/BigTree-CMS/commit/69885bf826f1c65615ae672288842e3339867d97
