### ISSUE TITLE
Relative paths breaking custom pending page previews

### ISSUE THREAD

**Issue by jmason03** [bigtreecms/BigTree-CMS#216]
I entered just "_preview.php" for the preview URL in one of my module views. I have a file saved in custom > modules > sidebars > _preview.php. The link/icon that gets added to the module view works fine but when coming from the pending changes screen it doesn't because it just adds it to the end of the URL and there is no file in that pending-changes path. I came up with a possible fix for it to be placed in pending-changes > default.php on line 195.

```

if ($view["preview_url"]) {
    $preview_url = filter_var($view["preview_url"], FILTER_VALIDATE_URL) ? rtrim($view["preview_url"],"/") . "/" . $item["id"] . "/" : ADMIN_ROOT . $view["table"] . "/" . rtrim($view["preview_url"],"/")."/".$item["id"]."/";
    <section class="changes_action"><a href="<?=$preview_url?>" target="_preview" class="icon_preview"></a></section>
}

```

This way, if the user enters a full/valid URL as the preview URL then that is used, otherwise a path to where the preview file should be located is set so that it looks in the right (default) place.

**Comment by timbuckingham** [comment]
I don't think I'm following entirely on the use case for _preview.php -- it looks like in the example code you entered it would render a link like:

http://localhost/bigtree/admin/my_table_name/_preview.php/15/

Am I missing something there?

We've generally used the preview URL functionality to allow for something like:
http://localhost/bigtree/news/_preview/15/ -- a URL that lets you view the pending module entry in the context of the front end of your site, though I assume you could also target a custom module endpoint in the admin like http://localhost/bigtree/admin/news/preview/15/.

**Comment by jmason03** [comment]
Sorry, there was a typo in my first post. I didn't enter "_preview.php" but rather just "_preview" so the generated link with the code I added in the first post is: http://localhost/bigtree/admin/my_table_name/_preview/15/

That being said, your example makes a lot of sense and seems like it might be the better route. I was assuming that previews for module entries had to live within the context of the admin. This is what is happening with my preview file in custom > modules > %module_name% > _preview.php. So when I click the preview icon, my preview file is loaded like the attached picture.

![sidebar_preview](https://cloud.githubusercontent.com/assets/5401264/10469280/ce1abb52-71c9-11e5-82a8-79cfe619f5cb.png)

I don't necessarily mind that that is how the preview is loaded. Obviously it doesn't look like the front end version but for this specific example it was more about making sure the links worked and were formatted correctly.

 So my new question is how do I load and where do I place my preview file if I want to see my preview on the front end side?

**Comment by timbuckingham** [comment]
In the past we've generally done this two ways. The first is for something with a detail page like a news article that is part of the news template. Say the news template lives at /news/ and the detail page for an article is usually /news/details/news-article-route/. We'd create another file inside the routed template directory called preview.php and link to /news/preview/ for the preview URL.

Inside of preview.php we would call:
BigTreeAutoModule::getPendingItem("my_news_table",$bigtree["commands"][0]);

That returns you with an array containing the item with pending changes applied, many to many connections that are pending, pending tags, the current publication status, and the current owner of the changes. We would then use that item with pending changes applied to draw the detail page just like we would normally and then throw an H2 or something noting that it was a preview.

The other way we approached it is for things like homepage gallery features -- we built out a whole template dedicated to just showing the homepage with the pending item selected. Same idea with using BigTreeAutoModule::getPendingItem.

If you need less context you could also stick your preview files in your /templates/ajax/ directory.

**Comment by jmason03** [comment]
Great, thanks for all the info! That makes a lot of sense. I had thought about trying to set it up that way but kind of got started one way and never looked into anything else. What I had setup was my preview file would find a page that my pending item was being used on and then I would redirect to the preview version of that entire page. I then had a little code added to my module's constructor so that it would get the data based on BIGTREE_PREVIEWING from either the pending changes table or the module's table.

But your way seems like a better approach so I think I'll switch it over to that. Thanks again for your help!
