### ISSUE TITLE
Module Route Access Ignored

### ISSUE THREAD

**Issue by randyhook** [bigtreecms/BigTree-CMS#217]
Scenario: I created a module, then assigned the Administrator Access Level to my View action. Logging into the admin panel as a Normal User, I was still able to access that route.

I could not find the code that checks the Access Level when serving up a request for a module action, only permission checks for access to the module as a whole. I added the following to the admin router:

```
if ($admin->Level < $route_response['action']['level']) {
    $admin->stop(file_get_contents(BigTree::path("admin/pages/_denied.php")));
}
```

Link to branch: https://github.com/MindscapeSolutions/BigTree-CMS/tree/module-route-access-fix

**Comment by timbuckingham** [comment]
Thanks for catching this!

I moved the $route_response capture to before the checkAccess call and incorporated the route level checking inside of checkAccess. That also drops a few database calls from happening in the event that you shouldn't have access.

https://github.com/bigtreecms/BigTree-CMS/commit/24372a2f0b9d0c35a99baf14f64b4195f082ace6
