### ISSUE TITLE
Updating an Extension Setting

### ISSUE THREAD

**Issue by randyhook** [bigtreecms/BigTree-CMS#220]
I believe I've found an issue with settings in an extension, but I may be missing something. Here's the scenario:

I have a setting in my extension com.mindscapesolutions.public-user called public-user-login-page. This is saved to the bigtree_settings table with an id of com.mindscapesolutions.public-user*public-user-login-page.

When I go to update the setting, nothing happens, and I traced it to line 25 of admin/modules/settings/update.php that looks like:

```
"input" => $bigtree["post_data"][$_POST["id"]]
```

My $bigtree["post_data"] (same as $_POST) looks like this:

```
array (size=4)
  'MAX_FILE_SIZE' => string '8388608' (length=7)
  '_bigtree_post_check' => string 'success' (length=7)
  'id' => string 'com.mindscapesolutions.public-user*public-user-home-page' (length=56)
  'com_mindscapesolutions_public-user*public-user-home-page' => string 'http://localhost/bt427/user-home/' (length=33)
```

You can see that the last item in the array has replaced the setting id's periods with underscores. Therefore, in line 25, there is no such index. I can't figure out why the post is replacing the periods with underscores in the first place.

For now, I've changed line 25 to:

```
"input" => $bigtree["post_data"][str_replace('.', '_', $bigtree["post_data"]["id"])],
```

**Comment by timbuckingham** [comment]
Sorry it took me so long to get back to you here. I've been sick so I've been out of it!

Honestly I have no idea why it was ever setup to use the setting's ID as the post key. I just switched it to always use "value" as the post key and that should resolve problems with extension settings!

See the above commit reference for the fix. Hopefully BigTree 4.2.8 will be out tomorrow as I'm wrapping up a lot of fixes into a release.

**Comment by randyhook** [comment]
Awesome! Looking forward to it.
