### ISSUE TITLE
BigTree and REST Api's

### ISSUE THREAD

**Issue by nmpribeiro** [bigtreecms/BigTree-CMS#221]
Hi there...

How is Big Tree able to handle rest api's? Anything out of the box, or should we aim for a module?

Thanks

**Comment by timbuckingham** [comment]
No native support for APIs. In the past I've seen people using a routed template to create an API.

**Comment by nmpribeiro** [comment]
I see... well, perhaps in the future then. Thanks @timbuckingham

**Comment by timbuckingham** [comment]
I just remembered this was discussed previously on the forums in case you'd like any more insight into it:
https://www.bigtreecms.org/forum/viewtopic.php?id=319

**Comment by nmpribeiro** [comment]
Yes. That's pretty informative for a newcomer like me.

**Comment by idivait** [comment]
I'm using React for a significant portion of my front-end work, so I ended up creating a file called 'api.php' within the ajax folder that returns different data based on different get parameters. The downside of this method for me right now is that it basically negates the preview functionality of BigTree. So, for instance, 

    $.ajax({
        url: "/ajax/api&action=grab_featured_person", 
        dataType:
        success: function(data){console.log(data)}
    });

would return the result of:

    function GrabFeaturedPerson($cms) {
        $home = $cms->getPage($home);
        $featured = $home[resources][featured];
        return $featured[0];
    }
    $value = GrabFeaturedPerson($cms);
    exit(json_encode($value));

Though my PHP is decent at best, so I'm certain there are better ways to do it. As a side note, you do need to add a CORS header to the file for that ajax call to function.

**Comment by timbuckingham** [comment]
You could augment your GrabFeaturedPerson function with preview functionality by doing something like:
```
function GrabFeaturedPerson($cms) {
    if ($_GET["preview"]) {
        $home = $cms->getPendingPage($home);
    } else {
        $home = $cms->getPage($home);
    }
    $featured = $home["resources"]["featured"];
    return $featured[0];
}
```

Then you just request /ajax/api/?action=grab_featured_person&preview=true

**Comment by idivait** [comment]
Hmm, good idea! Then I could just change the ajax call based on the /_preview/ url.
```javascript
var baseUrl = document.location.pathname;
var preview = baseUrl.includes('_preview') ? '&preview=true' : '';
$.ajax({
    url: "/ajax/api&action=grab_featured_person" + preview, 
    dataType: "json"
    success: function(data){console.log(data)}
});
```
Don't mind me while I go write that in...
