### ISSUE TITLE
Callout Default Display Label

### ISSUE THREAD

**Issue by jmason03** [bigtreecms/BigTree-CMS#223]
When creating a callout, the first resource is always checked automatically as the label. Obviously, this can easily be changed to a different resource but if there is not an appropriate choice, the user is not able to uncheck it and use the "Default Display Label". Should the first resource when creating a callout have the state of the radio button be left unchecked?

Also (and much more complicated), would it be better to have a way to uncheck the label designation after the callout is created? So a user could have a callout with a resource as a label for a period of time, but then uncheck that and just use "Default Display Label."

**Comment by timbuckingham** [comment]
What browser / OS are you experiencing this in? It should default every added resource to the "unchecked" state for the label radio button (though it is impossible to clear the state if you accidentally click on it -- maybe we could auto-clear the radio state if you start typing in the "Default Display Label" box).

**Comment by jmason03** [comment]
Well I thought it was happening and of course now I can't recreate it. I am on a different computer so maybe at work I was running an older version of Chrome. I believe I originally "saw" it while running Chrome on Windows 7 using BigTree 4.2.8. But I'm away from my office for awhile and on my laptop running Chrome with Windows 10 and BigTree 4.2.8, I'm not experiencing the issue anymore.

I do like the idea of disabling the active radio button if you type in Default Display Label. I can't think of any simpler/more intuitive way to let users switch back and forth.

**Comment by timbuckingham** [comment]
After actually implementing my solution I remembered... Default Display Label is still a good use case alongside the radio button'd option in case that field isn't filled out... so I went with a simpler option of just a "Clear Label" button.

https://github.com/bigtreecms/BigTree-CMS/commit/5df2cfcc335df474da82288244a7563fd5ed99e4
