### ISSUE TITLE
Request modules: Pages Top and Related

### ISSUE THREAD

**Issue by rd012a** [bigtreecms/BigTree-CMS#225]
It would good to have:
1. The module, Related Posts with Thumbnails, for installation in the bottom of the page.
2. Module, Popular Pages with Thumbnails, for display in the sidebar.

**Comment by timbuckingham** [comment]
Can you clarify what you're looking for? Like is this something you're looking for to show on the front end of the site or somewhere in the admin panel?

**Comment by rd012a** [comment]
Sorry, I'm probably wrong, to understand the device, of your cms. I was be confusing http://www.spymuseum.org/
I was looking for a modular system, with such design  plug-ins, such as, for wordpress
https://wordpress.org/plugins/top-10/screenshots/  -  Popular posts
https://ru.wordpress.org/plugins/related-posts-thumbnails/screenshots/  -  Related Posts

**Comment by timbuckingham** [comment]
Spy Museum does run on BigTree but BigTree's extensions system isn't very similar to WordPress' plugin system philosophically. We generally don't believe in presenting anything to the front end that can be easily done by a front end developer -- in this case you would probably create a callout and use the BigTreeCMS class' getRelatedPagesByTags method to find the related pages for the current page and draw them yourself in the sidebar.
