### ISSUE TITLE
Custom "Save & Preview" Route

### ISSUE THREAD

**Issue by jmason03** [bigtreecms/BigTree-CMS#228]
In auto-modules/forms/process.php when the user clicks "Save & Preview" if there is a custom preview URL specified by the user it is set on line 174:
$redirect_url = $view["preview_url"].$edit_id."/?bigtree_preview_return=".urlencode($bigtree["form_root"].$edit_id."/");

Should there be a / added before the $edit_id so that it is passed as a separate command in the URL rather than appended to the end of the user's preview url?

$redirect_url = $view["preview_url"]."/".$edit_id."/?bigtree_preview_return=".urlencode($bigtree["form_root"].$edit_id."/");

**Comment by timbuckingham** [comment]
I've just pushed a fix for this -- it looks like everywhere else that preview URL was being used it properly did an rtrim($view["preview_url"],"/")."/" but not in this one spot.

It should definitely be passed as a command rather than a portion of the URL :)

**Comment by jmason03** [comment]
Awesome! Thanks
