### ISSUE TITLE
Accept Image file types only (in upload form field when Image Uploader is enabled)

### ISSUE THREAD

**Issue by dantaex** [bigtreecms/BigTree-CMS#237]
When Image Uploader is enabled, "upload" form field is drawn without the `accept="image/*"` attribute, allowing users to upload any type of file even though is rejected on submission. I added this:

`<? if (!empty($field["options"]["image"])){ ?> accept="image/*" <? } ?>`

to core/admin/form-field-types/draw/upload.php

Updated it here:
https://github.com/dantaex/BigTree-CMS/tree/4.0_dantaex_branch

**Comment by timbuckingham** [comment]
Thanks! Fixed in the above commit.
