### ISSUE TITLE
Layout broken on Mac Firefox (latest)

### ISSUE THREAD

**Issue by davidnewcomb** [bigtreecms/BigTree-CMS#238]
All the admin tables are broken when viewing on Mac Firefox v 45.0 (latest).
As you can see from the screen shot the table wraps. This makes it particularly difficult to drag entries to different positions in order to do reordering.
The layout when viewed on Mac Safari is fine.

![screen shot 2016-03-15 at 02 57 17](https://cloud.githubusercontent.com/assets/951359/13766526/6a3ee8b0-ea5a-11e5-8c9e-4fe7a41088e7.png)

**Comment by timbuckingham** [comment]
I'm not seeing this behavior in Mac Firefox v45 on the demo site (http://demo.bigtreecms.org/admin/quotes/). Does it appear broken there for you?

**Comment by davidnewcomb** [comment]
Looks ok on that page!
I did a diff of the yours and mine (html page only), then merged changes across but mine was always broken.
Reinstalled into the top level folder in case the path was affecting it but still no luck.
Tried code from download area on your web site and git master and mine still looks like the screen shot.
Weird!

**Comment by timbuckingham** [comment]
It's possible that it's screwed up view styles.

If you go and edit the Quotes module in the Views list there will be a little blue icon with a magnifying glass. Click that and it'll take you into the editor that lets you resize columns. If it still looks screwed up in there try hitting the "Clear Existing Style" button. That will try to reset the column widths to be all equal.

**Comment by davidnewcomb** [comment]
Reinstalled with the "Slugs ending in /" to avoid that problem. I could not find the views list or magnifying glass. Went into the Developer section and hunted around for something similar but could find "Clear Existing Style". However I don't thing the problem is related to the Quotes section, I think it is a problem with the CSS generally at it appears on other sections of the site:
![screen shot 2016-03-18 at 10 42 56](https://cloud.githubusercontent.com/assets/951359/13875929/aad0b61a-ecf8-11e5-87de-35d35b3bce86.png)
![screen shot 2016-03-18 at 10 48 10](https://cloud.githubusercontent.com/assets/951359/13875937/b4778a22-ecf8-11e5-8d2c-dcfcdfad36c0.png)

**Comment by timbuckingham** [comment]
Very strange that it's rendering improperly for you. I do all my development in Firefox on a Mac so I'm not sure what's causing the rendering issues :(

**Comment by davidnewcomb** [comment]
Upgraded my xampp from 5.6.13 to 5.6.19 but no change. I did notice that when xampp launched after installation it loaded the page from http://myhost.local/. I have previously been installing BigTree from http://localhost/bigtree/install.php and (even on the new version) it was broken.
This time I installed from http://myhost.local/bigtree/install.php and it worked. So it is something to do with installing when the name is localhost.
Just done a quick check: http://localhost/bigtree/admin/quotes/ broken but http://mynetwork.local/bigtree/admin/quotes/ looks fine.

**Comment by timbuckingham** [comment]
That's very strange. My best guess is that it's something weird going on in the browser where it has some kind of special view cache at that URL (my copy works fine from /localhost/ in Firefox). Glad you've at least got it working from a different domain! I'd ask if you could check it from another computer on Firefox but since it only happens at /localhost/ I guess that's not an option :)
