### ISSUE TITLE
Sub pages are not shown in nav top level

### ISSUE THREAD

**Issue by davidnewcomb** [bigtreecms/BigTree-CMS#239]
Another strange one that appears to work on the demo site but not for me. When I create sub pages in a install of the tree demo, they do not appear in the nav bar for the parent page.
![screen shot 2016-03-15 at 04 56 06](https://cloud.githubusercontent.com/assets/951359/13768281/1687db8e-ea6c-11e5-853f-c89e7ee98def.png)

If I type in the url by hand then both of them show up as below:
![screen shot 2016-03-15 at 04 55 47](https://cloud.githubusercontent.com/assets/951359/13768288/24d9aec4-ea6c-11e5-9f43-b7804ee39b0f.png)

I have checked this on Safari and FF and it is broken in both. Looking at the source code for the page itself, the links to the sub pages are physically not there in the first page example.

**Comment by timbuckingham** [comment]
Hm, I'm taking a shot in the dark here but I'm guessing it has something to do with the navigation not reading your URL properly (and so it's not thinking that it's on the "My page" page).

What routing method did you install with (Basic, Simple Rewrite, Advanced)? What's your operating system / web server setup? Thanks!

**Comment by davidnewcomb** [comment]
Tried a few installs and determined that you are correct. If you install with "Advanced Routing + URLS End With Page Slug" it breaks. Not just with my My Page but also with the The Trees page too. This is probably why the "My Page" link in my first picture is not black: it hasn't been assigned the "active" class.

**Comment by timbuckingham** [comment]
Thanks for figuring that out! I've pushed up a commit that will fix this in the next release.
