### ISSUE TITLE
Missing admin-custom CSS/JS when using In-Page Editing

### ISSUE THREAD

**Issue by dantaex** [bigtreecms/BigTree-CMS#242]
When you create custom field types, you might want to add custom CSS and JS to the admin panel so these field types render properly to admins, you have to add CSS and JS in custom/settings.php like

`$bigtree["config"]["admin_js"]= array('my_custom_admin.js'	);`

Same for styles:

`$bigtree["config"]["admin_css"]= array('my_custom_admin.css');`

Said styles and scripts are added when you modify the page in BIgTree's admin panel, but **they are not added** when you're using In-Page Editing (when you click on that button in the left on the front-end toolbar):

![screenshot from 2016-03-26 00 37 51](https://cloud.githubusercontent.com/assets/4313950/14058595/3fa0f85c-f2eb-11e5-8a0c-1722df31a284.png)

The problem is that we have some code missing in core/admin/layouts/front-end.php
Fixed it here: 
https://github.com/dantaex/BigTree-CMS/commit/f8408add9a43361ce7e1d9a4e3573af1b0f09e45

**Comment by timbuckingham** [comment]
Thanks! Should be fixed in the upcoming 4.2.10 release.
