### ISSUE TITLE
Record Google Analytics $profile->PropertyID in DB

### ISSUE THREAD

**Issue by mdewyer** [bigtreecms/BigTree-CMS#243]
When setting a Google Analytics profile in Vitals & Statistics, save the $profile->PropertyID value to the bigtree-internal-google-analytics-api settings entry in the database, making it easy for frontend developers to access for outputting Javascript tracking code.

**Comment by timbuckingham** [comment]
Matt,

I apologize for not getting to this in what seems like forever. I have no idea why I missed it for so long! From what I can see, BigTree does store the profile in the bigtree-internal-google-analytics-api setting. Maybe I updated it per your request a year and a half ago and never responded? I have no idea! :)
