### ISSUE TITLE
Ability to drag and set order of tabs in module admin

### ISSUE THREAD

**Issue by mbriney** [bigtreecms/BigTree-CMS#247]
When a new view is added it's automatically added to the last tab of the module page.  It would be nice to be able to re-order the tabs in a sequence that is preferred, even if this was an override of the defaults.

**Comment by timbuckingham** [comment]
You should be able to re-order the navigation via drag & drop by adjusting the module's actions.

<img width="1067" alt="screen shot 2016-06-03 at 8 42 44 pm" src="https://cloud.githubusercontent.com/assets/1420086/15796461/cdd53a4a-29cb-11e6-8175-ad9eb3e6d652.png">

**Comment by timbuckingham** [comment]
Closing this dormant issue, let me know if you're still having trouble!
