### ISSUE TITLE
"Invalid argument supplied for foreach()" when getCalloutsInGroups returns null

### ISSUE THREAD

**Issue by davidnewcomb** [bigtreecms/BigTree-CMS#248]
When clicking the "Add Callout" button while editing the home page the following warning is presented when there are no matches for the `$group_id`.

> Warning: Invalid argument supplied for foreach() in /Applications/XAMPP/xamppfiles/htdocs/my-proj/bigtree2/core/inc/bigtree/admin.php on line 3016

You get slightly different errors in the cases of:

* Already having an existing callout

![bigtree-one-callout](https://cloud.githubusercontent.com/assets/951359/15844201/0d5f47a0-2c60-11e6-8c55-4f1dbb88d001.png)

* Or not having a callout (firebug'ed the style on the page to show the full message)

![bigtree-no-callout](https://cloud.githubusercontent.com/assets/951359/15844200/0d5d1836-2c60-11e6-96cb-973623c927fd.png)

**Comment by timbuckingham** [comment]
Fixed in merge:
https://github.com/bigtreecms/BigTree-CMS/commit/4f3b25664f02480d99f6acb650b0e790105824f3
