### ISSUE TITLE
Files affected by previous bug are not properly replaced

### ISSUE THREAD

**Issue by asiral** [bigtreecms/BigTree-CMS#259]
Regarding this previous bug:

"FIXED: Non-images being dumped into /files/ instead of /files/resources/"

When replacing the resources affected by this bug, the new file goes into /files/resources but the entry is not updated in the database.

**Comment by timbuckingham** [comment]
Unfortunately I don't have any beta/rc installs available to test this against. Are you referring to the 4.2 feature that lets you replace an existing file in the file manager?

**Comment by asiral** [comment]
Yes. Specifically, the feature implemented with the "Replace" button shown in the attached screenshot (from the demo site).
![screenshot from 2016-09-27 16 59 40](https://cloud.githubusercontent.com/assets/2885971/18874725/d9bd3534-84d3-11e6-9bbc-17b1fbbcd1ff.png)

**Comment by timbuckingham** [comment]
I can't think of a good way to fix this without a bunch of hacky code so I'm closing this for now. My recommendation would be to update the DB to correct any file locations if you're still running into the problem.
