### ISSUE TITLE
Flickr Service API not connecting properly

### ISSUE THREAD

**Issue by mbriney** [bigtreecms/BigTree-CMS#261]
On version 4.2.13 when attempting to connect to Flickr in the Service API developer panel the application authenticates properly but doesn't appear to be sending data back to BigTree correctly.  

Screenshot here, I'll try and post more debugging: 
http://mountvernon.clarify-it.com/d/meza47

**Comment by timbuckingham** [comment]
Just wanted to follow up and let you know that this is still on my radar, I've just been too stuck in other things to get my eyes on it!

**Comment by timbuckingham** [comment]
Sorry for the extraordinarily long delay on getting this fixed! It looks like Flickr deprecated the URL we were using for API calls. This should now be fixed in this commit:

https://github.com/bigtreecms/BigTree-CMS/commit/8d2d1bf89cefb629f8e3e3da5480137bfe01ee47
