### ISSUE TITLE
BigTree CMS 4.2.13 - Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by bestshow** [bigtreecms/BigTree-CMS#264]
[BigTree CMS 4.2.13 - Cross-Site Scripting (XSS).docx](https://github.com/bigtreecms/BigTree-CMS/files/615582/BigTree.CMS.4.2.13.-.Cross-Site.Scripting.XSS.docx)

**Comment by timbuckingham** [comment]
Fixed here:
https://github.com/bigtreecms/BigTree-CMS/commit/59ebef5978f80e2fdc7b4db4a28b668c5a39fbc3

Thanks!

**Comment by bestshow** [comment]
@timbuckingham If suitable for a CVE please assign one for this issue.
Thanks.
