### ISSUE TITLE
BigTree CMS 4.2.13 Extension Form Builder- Multiple Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by bestshow** [bigtreecms/BigTree-CMS#265]
[BigTree CMS 4.2.13 Extension Form Builder- Multiple Cross-Site Scripting (XSS).docx](https://github.com/bigtreecms/BigTree-CMS/files/615587/BigTree.CMS.4.2.13.Extension.Form.Builder-.Multiple.Cross-Site.Scripting.XSS.docx)

**Comment by timbuckingham** [comment]
This is now fixed here:
https://github.com/Fastspot/bigtree-form-builder/commit/06fde0cc67ff121b212715031e12574f50970fcd

**Comment by bestshow** [comment]
Could you please help me assign a CVE for this issue?

**Comment by bestshow** [comment]
@timbuckingham Please assign CVEs if you think they are suitable for identifiers.

**Comment by bestshow** [comment]
@timbuckingham Please assign CVEs if you think they are suitable for identifiers.
