### ISSUE TITLE
Social Feed edit query error on 4.2.14

### ISSUE THREAD

**Issue by matthisamoto** [bigtreecms/BigTree-CMS#266]
Saved a new query for Facebook, hit sync, nothing happened. Went back to edit query and found a broken image and a warning in place of where query was:
```
Warning: Illegal string offset 'name' in .../extensions/com.fastspot.social-feed/ajax/query-element.php on line 41
```

Though I'm not entirely sure the lack of sync had anything to do with this.

I put in a Facebook graph URL like this: `https://graph.facebook.com/v2.8/<PAGE ID>/feed`

**Comment by matthisamoto** [comment]
In addition, do I need to be concerned that Facebook is not one of the "Queryable Services" listed in Settings?

![screen shot 2016-12-08 at 11 35 30 am](https://cloud.githubusercontent.com/assets/547172/21018355/89be808e-bd3a-11e6-8b30-bffc784d9bbf.png)

**Comment by timbuckingham** [comment]
I've released a few updates to the Social Feed module that fixes the sync with Facebook, fixes the Queryable Services screen, and adds better error checking to the social queries so that you don't end up with an invalid page query that fails to sync. Sorry it took me so long!

**Comment by matthisamoto** [comment]
That is sweet I'll check it out. Thank you so much for looking into this!
