### ISSUE TITLE
automatically remove pertinent files after successful install

### ISSUE THREAD

**Issue by ReliefCrew** [bigtreecms/BigTree-CMS#267]
While automating http://pilotprogram.org we noticed the attached patch was rather helpful. So, thought to submit it for consideration :-)

Many thanks for a wonderful CMS!
[bigtree.patch.txt](https://github.com/bigtreecms/BigTree-CMS/files/672039/bigtree.patch.txt)

**Comment by timbuckingham** [comment]
Sorry for the delayed response here and thank you for the tip!

We've patched the installer to try to remove the install files (should work when running as FastCGI or suexec php) here: https://github.com/bigtreecms/BigTree-CMS/commit/48be774399c79f489c5920a18c709dcb9fe7a120
