### ISSUE TITLE
Contribution: Remove Version Number from Login Page

### ISSUE THREAD

**Issue by jefe317** [bigtreecms/BigTree-CMS#269]
Remove version number from admin login page to avoid exposing current version for security purposes.

[Issue](https://github.com/jefe317/BigTree-CMS/commit/1deee808854ede548c59096029f1e1ba5784ce5e)

**Comment by timbuckingham** [comment]
Sorry for the delay! Just pushed this into core.

**Comment by jefe317** [comment]
Thanks, Tim!
