### ISSUE TITLE
Contribution: Folder Info in File Browser

### ISSUE THREAD

**Issue by jefe317** [bigtreecms/BigTree-CMS#270]
Show folder info for files in file browser. Especially helpful for search to see where files are located.
[Issue](https://github.com/jefe317/BigTree-CMS/commit/d9e8238b80fb2514d220f125f47d129c086e7f93)
![bigtree-search-folder](https://cloud.githubusercontent.com/assets/173471/22513595/5380ec48-e862-11e6-8416-8304162a4ed6.PNG)

**Comment by timbuckingham** [comment]
Thanks for the suggestion! I've added this in and clicking on the folder name takes you to the folder the file is in.

**Comment by jefe317** [comment]
This is great, thanks, Tim!
