### ISSUE TITLE
Add 301 Redirect button no longer appearing

### ISSUE THREAD

**Issue by tbookwalter** [bigtreecms/BigTree-CMS#272]
When logging into the admin and going to the 404 Report page I am no longer able to see the "Add 301 Redirect" button with the green plus sign. When looking last week the button was there so this seems very odd. Do you know how we can get this button to reappear so we can add 301 redirects as needed? Thank you for your time and help.

**Comment by timbuckingham** [comment]
What version of BigTree are you running?

**Comment by tbookwalter** [comment]
Version 4.2.7

**Comment by timbuckingham** [comment]
I would upgrade to the latest 4.2 (I believe it's 4.2.15). The "Add 301 Redirect" button was added in BigTree 4.2.8.

**Comment by timbuckingham** [comment]
Closing this dormant issue, let me know if you're still having trouble!
