### ISSUE TITLE
How can I successfully upgrade from version 4.2.15 to 4.2.16 with BigTree blog function

### ISSUE THREAD

**Issue by AlexL777** [bigtreecms/BigTree-CMS#273]
Hello Developers,

I have a following problem. I use the version 4.2.15 at http://wpzweinull.ch/cms/bigtreecms and an older version with the blog function (BigTree-Blog) is installed. If I now upgrade the **/core** directory when upgrading, it shards me my website in the frontend.

Apparently, files and directories of the BigTree blog are also overwritten. How do I best manage and upgrade?

Thanks in advance.

**Comment by AlexL777** [comment]
I probably did something wrong. Now I have the upgrade on 4.2.16 made and logged in the backend. Now everything is all right again.

**Comment by timbuckingham** [comment]
Good to hear you got it worked out!
