### ISSUE TITLE
URL-Routing not worked - BigTree CMS v.4.2.16

### ISSUE THREAD

**Issue by AlexL777** [bigtreecms/BigTree-CMS#274]
Hello Developers,

After a long time I decided to buy a new BigTree website without the blog and now I created my first tree. Unfortunately, URL routing does not work properly.

Example is this tree URL, which can not be found.

https://bigtreecms.wpzweinull.ch/impressumdetail/einleitung-zu-diesem-bigtree-cms-projekt

`/impressumdetail/` in the URL is probably not at all, but how does it happen?

Maybe you can give me a quick help.

Thanks in advance, Alexander

**Comment by timbuckingham** [comment]
My best guess without the ability to look into the database or the code is that you're pointing to a detail page without the page path. I know the demo site uses /trees/detail/tree-name/ so I'm guessing you're missing the /trees/ portion of the URL.

**Comment by AlexL777** [comment]
Yes, I can recall having `/trees/` removed. Unfortunately I have now looked at all the settings and can not find this place anymore. Can you please help me and reveal where I must enter this URL part.

I also need to learn, so I need some tips on BigTree CMS.

Thanks in advance.

**Comment by timbuckingham** [comment]
Trees was a page in the Pages tree that used the Trees routed template.

**Comment by AlexL777** [comment]
Hm ... I find this somewhat complicated for beginners. So I have now managed to create a page for all trees. Please see it at https://bigtreecms.wpzweinull.ch/-trees-. In the navigation top right I can get to the tree with the correct path.

But the image on this trees page does not forward correctly to the tree. The URL part with -trees- is not created.

I use the trees template for this trees page.

The trees I create do not contain the URL part "-trees-". What am I doing wrong?

On the home page it is exactly the same. The trees do not have a correct URL.

Something I forget, but do not come to it myself. Do you have a tip perhaps?

**Comment by AlexL777** [comment]
Hello Developers,
I am still working on this issue. I have made a completely new installation of the BigTee CMS and now the sample trees are shown at https://bigtreecms.wpzweinull.ch/trees.

However, the URL to the tree itself does not match. This would be for example: https://bigtreecms.wpzweinull.ch/treesdetail/ich-teste-mal-die-trees-hier-im-blog/

Behind **/trees** is missing the `slash` and I do not know how I can adjust in the system. The trees template is already present and I use also with the Trees. But the slash is still missing.

Can you help me solve the problem?

Thanks in advance.
