### ISSUE TITLE
No csrf_token set in Image Option Presets

### ISSUE THREAD

**Issue by martijnmegens** [bigtreecms/BigTree-CMS#277]
1) Developer > Media > IMAGE OPTION PRESETS

Can't save, cause csrf_token fails, it's not set?

2) Users > Edit User > Permissions
There I see the csrf_token input field, but javascript still putsout an error:

> CSRFTokenField is not defined at Function.$.secureAjax (lib.js:116)

**Comment by timbuckingham** [comment]
Do you have a custom override for /core/admin/layouts/_header.php or for the BigTreeAdmin class?

The CRFTokenField value is set in that header file by referencing $admin->CSRFTokenField:

`<script>
	var CSRFTokenField = "<?=$admin->CSRFTokenField?>";
	var CSRFToken = "<?=$admin->CSRFToken?>";
</script>`

**Comment by martijnmegens** [comment]
That is exactly it :-) Thx alot

**Comment by timbuckingham** [comment]
No problem, happy to help!
