### ISSUE TITLE
Formatting does not work in frontend - what do

### ISSUE THREAD

**Issue by AlexL777** [bigtreecms/BigTree-CMS#278]
Hello Developers,

I have today again a new installation of BigTree CMS accomplished. When creating a tree in the backend, the H2 tags or the code tag work in the editor. But in the front end in the Chrome browser and Edge browser unfortunately not.

The Chrome Inspector has also found the H2 tags in the source code, but nothing is formatted in the frontend.

It's BigTree 4.2.17.

Can you see this again. Thanks in advance.

This ist under https://bigtreecms.wpzweinull.ch/trees/detail/projektstart-mit-bigtree-opensource-cms/

**Comment by timbuckingham** [comment]
The demo site doesn't have front-end styles for H2/H3/H5/H6 but they can be added by editing /site/css/master.css beginning at line 30.
