### ISSUE TITLE
Switch TinyMCE to browser_spellcheck

### ISSUE THREAD

**Issue by mcongrove** [bigtreecms/BigTree-CMS#303]
According to [TinyMCE docs](https://www.tinymce.com/docs/configure/spelling/), "Gecko Spell Check was deprecated in TinyMCE v4.3".

`gecko_spellcheck: true` should become `browser_spellcheck: true`.

**Comment by timbuckingham** [comment]
Thanks! Should be fixed in 4.2-devel now
