### ISSUE TITLE
Problem on installing cms

### ISSUE THREAD

**Issue by rfum** [bigtreecms/BigTree-CMS#321]
I've just dowloaded the latest version.I'm trying to install the cms at my linux machine but install php page looks weird seems like some php block is not closed properly. It seems it pastes the php code as html. .Here is the screenshots : 
![img1](https://user-images.githubusercontent.com/18735243/31840470-3063b16e-b5ee-11e7-819a-603e7d4142a0.png)
![img2](https://user-images.githubusercontent.com/18735243/31840472-30e39e2e-b5ee-11e7-927f-3d184b15cf67.png)
![img3](https://user-images.githubusercontent.com/18735243/31840475-3177aa2e-b5ee-11e7-9be3-8211325faacf.png)
![img4](https://user-images.githubusercontent.com/18735243/31840476-319ecef6-b5ee-11e7-9ced-43bbe81c51fc.png)
![img5](https://user-images.githubusercontent.com/18735243/31840477-31c0fea4-b5ee-11e7-959d-26114fe2f22a.png)

**Comment by timbuckingham** [comment]
It looks like your server isn't parsing the PHP file as PHP but rather just rendering everything as HTML.

**Comment by rfum** [comment]
ahh my bad i've got some missing dependencies at my machine to make php7 compatible with apache2 thanks for quick response problem solved.

**Comment by timbuckingham** [comment]
Happy to help!
