### ISSUE TITLE
TinyMCE CSS loading

### ISSUE THREAD

**Issue by mbriney** [bigtreecms/BigTree-CMS#325]
We're getting an error in the TinyMCE editor in BigTree:
Failed to load content css: http://[DOMAIN]/css/tinymce.css

It seems to be related to this issue in the TinyMCE and was fixed in a subsequent version.  Would it be possible to look at a refresh of TinyMCE in a future BigTree release?
https://github.com/tinymce/tinymce/issues/3763

**Comment by timbuckingham** [comment]
I just pushed up an update to the 4.2-devel branch that includes TinyMCE 4.7.4 -- can you give the 4.2-devel branch a try and see if it resolves that error?
