### ISSUE TITLE
no htaccess files?

### ISSUE THREAD

**Issue by neosin** [bigtreecms/BigTree-CMS#330]
I downloaded and installed latest release
Everything works however I notice in the URL index.php for all paths
example: http://demo.com/site/index.php/admin/
I need to remove index.php from all urls but there are no htaccess files anywhere in the entire project. How do I remove index.php from all urls?

**Comment by timbuckingham** [comment]
During the installer you have the option of Basic, Simple Rewrite, or Advanced routing. The Simple Rewrite or Advanced options will install an htaccess file that removes /site/index.php from the URLs.

**Comment by neosin** [comment]
aha!
thank you sir
