### ISSUE TITLE
File Info: Show user who uploaded file

### ISSUE THREAD

**Issue by jefe317** [bigtreecms/BigTree-CMS#338]
It would be helpful to be able to see which user uploaded a file, even if it was just in the database and not the file browser. We're doing an audit and it's difficult to see who did what when it comes to file ownership.

**Comment by timbuckingham** [comment]
I don't think there's presently an easy way to view it in the audit trail viewer (will fix in 4.3!) but this data is logged in the bigtree_audit_trail table -- search for table = bigtree_resources and it will give you a list of all actions taking place in the file manager.

**Comment by jefe317** [comment]
Thanks, Tim! This is indeed doable with a few inner joins in mysql, thanks!
