### ISSUE TITLE
Authenticated Directory Traversal in BigTree-CMS 4.2.23

### ISSUE THREAD

**Issue by zionspike** [bigtreecms/BigTree-CMS#350]
The CMS allows an authenticated administrator and developer to call an Ajax, which allow them to list files and directories for a particular directory.

The following are example HTTP request:

```
POST /test/BigTreeCMS-4.2.23/BigTree-CMS/site/index.php/admin/ajax/developer/extensions/file-browser HTTP/1.1
...snip..
Cookie: <admin/dev cookies>
...snip..

location=server&directory=../../
```

The vulnerable code: BigTree-CMS\core\admin\ajax\developer\extensions\file-browser.php
```
45: opendir $o = opendir($directory); 
41: $directory = SERVER_ROOT . $postdirectory; 
36: $postdirectory = $_POST['directory'];
```

**Comment by zionspike** [comment]
You're saying that the issue is functional that allow developer users to list directories and files in a particular directory even above root directory. If so I'll agree and close this thread.

**Comment by timbuckingham** [comment]
Yes, that is correct!

**Comment by zionspike** [comment]
Close the issue
