### ISSUE TITLE
Make session cookie params configurable. 

### ISSUE THREAD

**Issue by ddrozdik** [bigtreecms/BigTree-CMS#355]
Hi,

I noticed that CMS does not provide the possibility override session cookie parameters that currently hardcoded here 
https://github.com/bigtreecms/BigTree-CMS/blob/3f7effb8433bd785032067863642da1fe08f3b70/core/inc/bigtree/sessions.php#L87

On the project, we work we had a necessity to set a secure flag to TRUE instead of FALSE. Due to the limitation in the CMS, we had to override the whole file to change only one parameter. 

I would suggest to move all these parameters into the config.settings.php and allow to override default values if a project requires so.

**Comment by mbriney** [comment]
To further clarify Dmitry’s request.  This came up as a necessary requirement of our site’s PCI compliance.  It would be very helpful to have this as a configurable option.

**Comment by timbuckingham** [comment]
Thanks for the suggestion and clarification! I've pushed commits to both the 4.2 and 4.3 branches that should enable this as a configuration option:

https://github.com/bigtreecms/BigTree-CMS/commit/ab8ab362a4372b3e0c3bb536903ac24715be9703
https://github.com/bigtreecms/BigTree-CMS/commit/9f204fc53ef9bc7c1a43126851ffe8180a478203

Setting $bigtree["config"]["ssl_only_session_cookie"] to a non-false value should turn on SSL-only session cookies in the next releases of BigTree.
