### ISSUE TITLE
Suggestion: add url versioning to BigTreeCMS admin js and css URLs.

### ISSUE THREAD

**Issue by mbriney** [bigtreecms/BigTree-CMS#358]
A thought for consideration.

When we do a BigTreeCMS update where there has been a change to the JS or CSS files we have noticed that sometimes users are still browser caching the previous version of the JS and CSS files.

A potential way to prevent this could be with future core versions to add the BigTreeCMS version number to the URL of the asset (i.e. https://www.yoursite.com/admin/js/main.js?v4.4)

**Comment by timbuckingham** [comment]
This is a fantastic idea! I've run into it so many times I'm amazed it took someone else to point out how silly it was that we didn't cache bust CSS/JS in the admin based on version :)

https://github.com/bigtreecms/BigTree-CMS/commit/963be40a6e2cb50b267703a8c52bd3c0425e1cf4

Should be in 4.4.1 which will go out soon!
