### ISSUE TITLE
Can't get past composer update warning

### ISSUE THREAD

**Issue by mbriney** [bigtreecms/BigTree-CMS#365]
We're trying to set up a new local dev environment.  We've cloned our repository and symlinked bigtree/core to /core.  We're using BigTree 4.4

Visiting our dev site URL we get the error:

> BigTree has updated your composer.json file with required libraries. Please run `composer update` before attempting to use BigTree 4.3.

Running composer update doesn't do anything as all packages are current.

Any thoughts, it's very strange that it would be not indicating the proper version.

**Comment by timbuckingham** [comment]
Does it go away after a refresh? It should create a /cache/composer-check.flag file after displaying that message. After that file exists it should go away. If it's not going away it's possible that /cache/ isn't writable.

**Comment by mbriney** [comment]
Bingo, cache folder wasn't established or writeable.  That solved it.

**Comment by timbuckingham** [comment]
Sweet!
