### ISSUE TITLE
Background storage xss

### ISSUE THREAD

**Issue by MisakiKata** [bigtreecms/BigTree-CMS#368]
Background storage xss

Use normal users: qwe to send in-site messages to developers

![1559639787289](https://user-images.githubusercontent.com/27627614/58868577-31a95f00-86ef-11e9-8a6e-2f088a292bf7.png)

Capture packet modification parameters

![1559639850418](https://user-images.githubusercontent.com/27627614/58868586-366e1300-86ef-11e9-9e43-f5fa1cee0f41.png)

Can trigger on the developer side：
![1559639935656](https://user-images.githubusercontent.com/27627614/58868598-3e2db780-86ef-11e9-9ee2-511410d254e1.png)

**Comment by timbuckingham** [comment]
Thanks for the report, this has been fixed in the referenced commit above!
