### ISSUE TITLE
Files not saving in folders

### ISSUE THREAD

**Issue by mbriney** [bigtreecms/BigTree-CMS#370]
There seems to be a bug in 4.4.4 where uploading a PDF to a folder in files seems to only add it to the root.  Images this is not the case, images remain in the proper folder.

**Comment by timbuckingham** [comment]
I'm not able to replicate this locally -- do you mind if I poke around in your dev environment to see if it's environment specific? Thanks!

**Comment by mbriney** [comment]
That would be fine.
