### ISSUE TITLE
Moving Module Pages

### ISSUE THREAD

**Issue by mbriney** [bigtreecms/BigTree-CMS#371]
We have a scenario where a module page was moved to a different location, altering all of the URLs.  It seems that when this is done any subfolders are not directed either.

I tried setting up a page with an external link but that only redirects the root.  It does not pass in any subfolders.  I also tried the redirect module and it does the same operation.

i.e. /**digital-encyclopedia/**article/mary-ball-washington/ -> /library/digitalhistory/**digital-encyclopedia/**article/mary-ball-washington/

**bold** is the module page path

Is there any method without adding a redirect to the htaccess that would accomplish this natively in the CMS?

**Comment by timbuckingham** [comment]
No, unfortunately not. I'd go with a wildcard redirect in .htaccess. Unfortunately, I can't think of a way that the CMS could predict all the possible routes off of a routed template to facilitate automating the redirects.
