### ISSUE TITLE
Users - Content Alert

### ISSUE THREAD

**Issue by doonmok** [bigtreecms/BigTree-CMS#372]
Found an issue with All Pages Content Alerts not showing as checked after updating. 

Edit a users permission
Clicking checkbox Content Alert for All Pages
Update

In the table(bigtree_users), column alerts, it saves it as "undefined": "on".
But in the core/admin/modules/users/edit.php file, it is looking for $alerts[0] instead of $alerts["undefined"]. 

That is why All pages is not checked after updating a user. 

edit.php, on lines 291 and 302 should be updated to $alerts["undefined"].

**Comment by timbuckingham** [comment]
Hi Doon,

Sorry for the long delay on this one, I just pushed up a fix for it in the referenced commit above. Thanks for the bug report!
