### ISSUE TITLE
PDFs not uploading

### ISSUE THREAD

**Issue by mbriney** [bigtreecms/BigTree-CMS#375]
We seem to be having an issue of not being able to upload PDF through the files interface.  We can add the file to the upload queue but it doesn't let us continue.  Is there some type of file restriction setting somewhere that we need to adjust? 

![Image of error](https://i.imgur.com/J9n0y5B.png)

**Comment by timbuckingham** [comment]
Matt,

That's a very oddly named file — have you tried renaming it and seeing if it uploads successfully? If that does fix it can you provide me with the name of the file so I can see if it's something I can resolve in the future?

Thanks!

**Comment by mbriney** [comment]
Hi Tim,

It doesn't matter what the file is named they all seem to fail.

Any ideas?

Thanks
Matt

**Comment by timbuckingham** [comment]
Matt,

To clarify, is this happening with all PDFs regardless of what their filename is (before .pdf), all files in general, or just this specific file (no matter what it's named)?

Thanks!

**Comment by mbriney** [comment]
Hi @timbuckingham this is for all PDFs.

**Comment by chethiya44** [comment]
No @mbriney  pdf uploading working,
