### ISSUE TITLE
PHP 8 support?

### ISSUE THREAD

**Issue by JordivdB** [bigtreecms/BigTree-CMS#377]
Hi There,

I have been using Bigtree CMS in several projects over the past few years. I think it still is a decent option to choose as CMS but only if there is any development still going on.

I tried installing BigTree on a server running PHP 8, no suprise it didnt run, but the amount of errors was quite much. I personally don't have the time to find and fix them all. Are there any plans on bringing BigTree PHP 8 compatibility?

**Comment by timbuckingham** [comment]
Hello!

I haven't had a chance to try out PHP 8 yet but I'll give it a spin soon and see if I can shake out all the issues in BigTree. I've been meaning to get a 4.5 release out with a few features that are hanging out in that branch. Sorry for the quiet nature of the project lately -- it's not entirely dead, though!

**Comment by JordivdB** [comment]
@timbuckingham Good to hear you (and the project) are still alive. I'll keep following the progress. If i find the time i might do some pull requests.
