### ISSUE TITLE
Approve pending page, unchecks Visible in Navigation

### ISSUE THREAD

**Issue by doonmok** [bigtreecms/BigTree-CMS#380]
Found a bug when approving a page from a user that has Editor rights, does not keep Visible In Navigation checked. It only seems to happen when I'm approving a user's change that has Editor rights and the parent ID is 0.

For example
User edits/saves a page that's parent is 0. Different user with publishing rights goes to Dashboard > Pending Changes and approves the change. The Visible in Navigation is not checked anymore when it should be.

If a user with publisher rights, edits/saves and then goes to approve change, Visible in Navigation is still checked.

**Comment by doonmok** [comment]
Tim, I think I found the issue. When the Visible in Navigation checkbox is disabled, http does not post disabled inputs. That's why when I was looking at $_POST array, there was no in_nav key. But if it wasn't disabled, there was an in_nav key. 

I'm not sure what the best solution is but this is what I found.
https://stackoverflow.com/questions/4727974/how-to-post-submit-an-input-checkbox-that-is-disabled

**Comment by timbuckingham** [comment]
I apologize for the long delay in responding to this — I was just going back through issues and noticed I hadn't resolved it! I pushed a fix up for this in 4.5-devel that should be fixed in the next release (which should be tomorrow).
