### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by dwene** [bigtreecms/BigTree-CMS#381]
Is there still active development on BigTree CMS or has it moved to maintenance mode?

**Comment by timbuckingham** [comment]
It is mostly in maintenance mode. There will continue to be bug fix releases and I'm working on a PHP 8 release that has a few features that were started a while ago. BigTree 5 I would consider a dead branch — it's unlikely to ever find release. It has a lot of great code in place but the back-end admin interface changes were a bit too ambitious and the project no longer has a company sponsoring it so I don't have the hours to push it over the line.

**Comment by dwene** [comment]
Bummer, we're sorry to hear that. We've been working alot with Directus recently that seems to be a good headless CMS for us. 

Thanks for the information, and good luck!
