### ISSUE TITLE
AWS error

### ISSUE THREAD

**Issue by doonmok** [bigtreecms/BigTree-CMS#386]
I'm getting the error below when editing a module with an image, editing a page with image and when going to developer>cloud storage. This is on my local machine, do I need to add a time zone somewhere? 
My environment.php file has "date_default_timezone_set("America/Chicago");"

Fatal error: Uncaught InvalidArgumentException: Missing required client configuration options: region: (string) A "region" configuration value is required for the "s3" service (e.g., "us-west-2"). A list of available public regions and endpoints can be found at http://docs.aws.amazon.com/general/latest/gr/rande.html. in C:\MAMP\htdocs\upgrade\vendor\aws\aws-sdk-php\src\ClientResolver.php:371 Stack trace: #0 C:\MAMP\htdocs\upgrade\vendor\aws\aws-sdk-php\src\ClientResolver.php(267): Aws\ClientResolver->throwRequired(Array) #1 C:\MAMP\htdocs\upgrade\vendor\aws\aws-sdk-php\src\AwsClient.php(158): Aws\ClientResolver->resolve(Array, Object(Aws\HandlerList)) #2 C:\MAMP\htdocs\upgrade\vendor\aws\aws-sdk-php\src\S3\S3Client.php(261): Aws\AwsClient->__construct(Array) #3 C:\MAMP\htdocs\upgrade\core\inc\bigtree\apis\cloud-storage.php(1172): Aws\S3\S3Client->__construct(Array) #4 C:\MAMP\htdocs\upgrade\core\inc\bigtree\apis\cloud-storage.php(89): BigTreeCloudStorage->setupAmazon() #5 C:\MAMP\htdocs\upgrade\core\inc\bigtree\a in C:\MAMP\htdocs\upgrade\vendor\aws\aws-sdk-php\src\ClientResolver.php on line 371

**Comment by doonmok** [comment]
I just upgraded to 4.4.16

**Comment by timbuckingham** [comment]
I believe that's saying that your S3 environment doesn't have a region configured. I'd head over to the Developer tab first (to make sure the database upgrades have run) and if it still occurs go into the Cloud Storage configuration and make sure you have a region selected. If one is already set, try saving it again to see if that fixes the error.

**Comment by doonmok** [comment]
Cloud storage is getting the same error. Went to developer first and the cloud storage

**Comment by timbuckingham** [comment]
I would try deleting the "bigtree-internal-cloud-storage" and "bigtree-internal-storage" settings from the bigtree_settings table and then going through the cloud storage setup again. That should get you a fresh storage setup that doesn't try to infer a region.

**Comment by doonmok** [comment]
That worked, thanks Tim.
Only thing I'm worried about is this happening on our live website because we have to copy/paste over core folder since we always get a timed out when upgrading through bigtree. Think its bc our database is too big. 

I tried upgrading through bigtree on a different local website and no issues but the database is much smaller.

**Comment by timbuckingham** [comment]
I'd recommend upgrading BigTree through git. What I usually do is have the BigTree repository cloned into a `bigtree` folder and then symlink `bigtree/core` to `core`. Then to upgrade BigTree you just cd into the `bigtree` directory and do a git pull followed by logging into the admin to get the database upgraded. From what I can remember, there's been very few database upgrades in the past year or so to the 4.4 branch but I guess it depends on how far back the site is. They're done in ajax chunks though so they hopefully won't ever timeout.

**Comment by doonmok** [comment]
Thanks Tim, I will look into upgrading through git.

**Comment by doonmok** [comment]
Tim, I just upgraded two dev websites, one through bigtree and other by copy/paste and both got this issue. What was odd is it looked like there were issues but when I closed browser and opened back up, error came up.

**Comment by timbuckingham** [comment]
Hey doon,

Again sorry for the ridiculously long delay in responding to this. Are you still running into the problem after all this time?
