### ISSUE TITLE
Hello - hope you're still there!

### ISSUE THREAD

**Issue by newmedicine** [bigtreecms/BigTree-CMS#393]
Hi, after many years of wrangling with CMSs I have just stumbed across bigtree. Don't know how I missed it, as it seems a perfect fit for my non-profit - user-userable and developer-transparent.

It seems to do pretty much everything I need - but - is it alive? At least maintenance mode for security issues.

Thank you so much

Nick

**Comment by timbuckingham** [comment]
Hi Nick!

Yes, we're still actively maintaining BigTree. I push some fixes to the 4.5-devel branch every few days (patching up PHP 8.1+ support to remove warnings and other issues). We should have another 4.5 release out sometime in the next few weeks.
