### ISSUE TITLE
Add CC and BCC to BigTreeEmailService's sendEmail function

### ISSUE THREAD

**Issue by jemaleddin** [bigtreecms/BigTree-CMS#396]
BigTree::sendEmail has the following arguments:

`$to, $subject, $html, $text = "", $from = false, $return = false, $cc = false, $bcc = false, $headers = [], $ = []`

BigTreeEmailService's sendEmail meanwhile:

`$subject, $body, $to, $from_email = false, $from_name = false, $reply_to = false, $text = ""`

Seems like having CC and BCC would be great!

**Comment by timbuckingham** [comment]
Adding here!
https://github.com/bigtreecms/BigTree-CMS/commit/dd76cdf749e2f62d5fdbc8a5d60cd2a6c904ff67
