### ISSUE TITLE
Optional arguments should be specified after any required arguments

### ISSUE THREAD

**Issue by tm8544** [bigtreecms/BigTree-CMS#397]
BigTree-CMS\vendor\oyejorge\less.php\lib\Less\Tree\Directive.php

line 20: 	`public function __construct($name, $value = null, $rules, $index = null, $currentFileInfo = null, $debugInfo = null ){`

There is a required argument ($rules) in the middle of optional arguments. Note that any optional arguments should be specified after any required arguments.

Change  line 20 to e.g. 	`public function __construct($name, $value = null, $rules = null, $index = null, $currentFileInfo = null, $debugInfo = null ){`

**Comment by timbuckingham** [comment]
This is fixed in this commit to 4.5-devel:
https://github.com/bigtreecms/BigTree-CMS/commit/ff3615c87d0ad849d4e83889396439b58d96a397

We had to switch to the newer Wikimedia supported fork of Less.php since I didn't want to monkey patch a composer package.
