### ISSUE TITLE
BigTree 2FA QR Code Broken

### ISSUE THREAD

**Issue by emmyhensley** [bigtreecms/BigTree-CMS#403]
Hi there,

I'm being prompted to set up 2FA through BigTree and no QR code is populating for me to do so. I've tried refreshing the page, using a different browser, and using incognito mode. Thanks in advance for your help!

-Emmy
![Screenshot 2024-04-26 112900](https://github.com/bigtreecms/BigTree-CMS/assets/168216280/c0c35060-cdb0-4ab0-bd2b-4a8e830535fd)

**Comment by timbuckingham** [comment]
This should now be resolved in BigTree 4.5.11
